### PR TITLE
Add disableOutsideClick prop

### PR DESCRIPTION
**Pull request by roonie007**
this should solve #43

### CODE REVIEW

**Comment by roonie007** [comment]
Commit [a66c796](https://github.com/mbj36/vue-burger-menu/pull/44/commits/a66c7966720d187e7e1d31bac6d1752bbf19bead) and [871d82f](https://github.com/mbj36/vue-burger-menu/pull/44/commits/871d82f5f10be90d62aad05bc3adad8d4ad53ff0) should fix the closed issue #37 which is not fixed acutally.

Commit [fd20b5f](https://github.com/mbj36/vue-burger-menu/pull/44/commits/fd20b5f6bb5176d5797044595c8552ef5d90f140) should fix #40

**Comment by roonie007** [comment]
@mbj36 we don't really need to do any refs in the other files, since there is no interaction with the sideNav itself

**Comment by roonie007** [comment]
@mbj36 Any idea when this will be merged ?

**Comment by mbj36** [comment]
Thanks @roonie007 , Sorry for the delay

**Pull request merged**
